In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
buy = pd.read_csv('../../data/buy_data.csv') # 구매이력
history = pd.read_csv('../../data/history_data.csv') # 시청 시작 데이터
watch = pd.read_csv('../../data/watch_e_data.csv') # 시청 종료 데이터
meta = pd.read_csv('../../data/meta_data.csv') # 콘텐츠 일반 메타
meta_plus = pd.read_csv('../../data/meta_data_plus.csv') # 콘텐츠 확장 정보
profile = pd.read_csv('../../data/profile_data.csv') # 프로필 정보
search = pd.read_csv('../../data/search_data.csv') # 검색을 통한 시청 데이터
sample = pd.read_csv('../../data/sample_submission.csv')

/var/folders/fb/fgwpc_kd3dxdcfsnm_9w3wv40000gn/T/ipykernel_74471/1069480069.py:4: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  meta = pd.read_csv('../../data/meta_data.csv') # 콘텐츠 일반 메타

In [4]:
history

,profile_id,ss_id,log_time,act_target_dtl,album_id,payment,continuous_play,short_trailer
0,3,20220301115653,20220301115719,MKID003,15,NaN,Y,N
1,3,20220301115653,20220301115809,MKID003,16,NaN,Y,N
2,3,20220301115653,20220301115958,MKID003,17,NaN,Y,N
3,3,20220301115653,20220301120118,MKID003,18,NaN,Y,N
4,3,20220301115653,20220301120229,MKID003,19,NaN,Y,N
...,...,...,...,...,...,...,...,...
1005646,33032,20220427155091,20220427155668,MKID003,381,NaN,Y,N
1005647,33032,20220427155091,20220427155680,MKID003,381,NaN,Y,N
1005648,33032,20220427155839,20220427155810,MKID003,125,NaN,Y,N
1005649,33032,20220427155706,20220427155838,MKID003,125,NaN,Y,N
1005650,33032,20220427155865,20220427155891,MKID003,381,NaN,N,N

In [5]:
profile

,profile_id,sex,age,pr_interest_keyword_cd_1,pr_interest_keyword_cd_2,pr_interest_keyword_cd_3,ch_interest_keyword_cd_1,ch_interest_keyword_cd_2,ch_interest_keyword_cd_3
0,3,F,5,P02,P04,P07,K01,K03,K04
1,5,M,5,P07,P08,P06,K05,K08,K09
2,7,F,9,P05,P03,NaN,K06,K04,NaN
3,12,M,6,P03,P06,P02,K09,K07,K03
4,16,F,12,P03,P06,P01,K01,K06,K04
...,...,...,...,...,...,...,...,...,...
8306,33022,M,1,P04,NaN,NaN,K04,K08,NaN
8307,33023,M,5,P06,P03,P07,K08,K04,K05
8308,33026,F,8,P01,P03,P08,K05,K09,K06
8309,33027,F,4,P04,P05,P06,K03,K01,K05
8310,33032,F,5,P03,P05,P07,K01,K05,K09

In [23]:
df_merge = history.merge(profile,how='left',on='profile_id')
df_merge

,profile_id,ss_id,log_time,act_target_dtl,album_id,payment,continuous_play,short_trailer,sex,age,pr_interest_keyword_cd_1,pr_interest_keyword_cd_2,pr_interest_keyword_cd_3,ch_interest_keyword_cd_1,ch_interest_keyword_cd_2,ch_interest_keyword_cd_3
0,3,20220301115653,20220301115719,MKID003,15,NaN,Y,N,F,5,P02,P04,P07,K01,K03,K04
1,3,20220301115653,20220301115809,MKID003,16,NaN,Y,N,F,5,P02,P04,P07,K01,K03,K04
2,3,20220301115653,20220301115958,MKID003,17,NaN,Y,N,F,5,P02,P04,P07,K01,K03,K04
3,3,20220301115653,20220301120118,MKID003,18,NaN,Y,N,F,5,P02,P04,P07,K01,K03,K04
4,3,20220301115653,20220301120229,MKID003,19,NaN,Y,N,F,5,P02,P04,P07,K01,K03,K04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005646,33032,20220427155091,20220427155668,MKID003,381,NaN,Y,N,F,5,P03,P05,P07,K01,K05,K09
1005647,33032,20220427155091,20220427155680,MKID003,381,NaN,Y,N,F,5,P03,P05,P07,K01,K05,K09
1005648,33032,20220427155839,20220427155810,MKID003,125,NaN,Y,N,F,5,P03,P05,P07,K01,K05,K09
1005649,33032,20220427155706,20220427155838,MKID003,125,NaN,Y,N,F,5,P03,P05,P07,K01,K05,K09
1005650,33032,20220427155865,20220427155891,MKID003,381,NaN,N,N,F,5,P03,P05,P07,K01,K05,K09

# 가장 많이 시청하는 주 고객군

In [27]:
df_merge.groupby('age').size()

age
1      19923
2      95089
3     237275
4     208157
5     115880
6      94814
7      78303
8      79104
9      33236
10     15091
11      5314
12      5864
13     17601
dtype: int64

In [34]:
df_merge[(2<df_merge['age']) & (df_merge['age']<6)]

,profile_id,ss_id,log_time,act_target_dtl,album_id,payment,continuous_play,short_trailer,sex,age,pr_interest_keyword_cd_1,pr_interest_keyword_cd_2,pr_interest_keyword_cd_3,ch_interest_keyword_cd_1,ch_interest_keyword_cd_2,ch_interest_keyword_cd_3
0,3,20220301115653,20220301115719,MKID003,15,NaN,Y,N,F,5,P02,P04,P07,K01,K03,K04
1,3,20220301115653,20220301115809,MKID003,16,NaN,Y,N,F,5,P02,P04,P07,K01,K03,K04
2,3,20220301115653,20220301115958,MKID003,17,NaN,Y,N,F,5,P02,P04,P07,K01,K03,K04
3,3,20220301115653,20220301120118,MKID003,18,NaN,Y,N,F,5,P02,P04,P07,K01,K03,K04
4,3,20220301115653,20220301120229,MKID003,19,NaN,Y,N,F,5,P02,P04,P07,K01,K03,K04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005646,33032,20220427155091,20220427155668,MKID003,381,NaN,Y,N,F,5,P03,P05,P07,K01,K05,K09
1005647,33032,20220427155091,20220427155680,MKID003,381,NaN,Y,N,F,5,P03,P05,P07,K01,K05,K09
1005648,33032,20220427155839,20220427155810,MKID003,125,NaN,Y,N,F,5,P03,P05,P07,K01,K05,K09
1005649,33032,20220427155706,20220427155838,MKID003,125,NaN,Y,N,F,5,P03,P05,P07,K01,K05,K09
1005650,33032,20220427155865,20220427155891,MKID003,381,NaN,N,N,F,5,P03,P05,P07,K01,K05,K09

# 연령대 별로 가장 많이 시청하는 영상

In [35]:
groupby = df_merge.groupby(['album_id','age']).size().reset_index().rename(columns={0:'count'})
groupby

       album_id  age  count
0             0    1     52
1             0    2    105
2             0    3    376
3             0    4    337
4             0    5    218
...         ...  ...    ...
80828     25912    1     57
80829     25913    1      1
80830     25914    1      1
80831     25915    1      1
80832     25916    1      1

[80833 rows x 3 columns]

In [37]:
groupby.sort_values(by='count')

       album_id  age  count
40416      6154    8      1
48529      7949    8      1
48530      7950    2      1
48534      7950    8      1
48544      7953    5      1
...         ...  ...    ...
158          16    2   2887
172          17    3   2965
195          19    3   3143
147          15    3   3807
159          16    3   5510

[80833 rows x 3 columns]

## 연령대 별로 한번 혹은 두번만 시청된 영상

In [39]:
groupby[groupby['count'] == 1]

       album_id  age  count
21            1   10      1
22            1   11      1
35            3    2      1
43            3   13      1
54            5    1      1
...         ...  ...    ...
80827     25898    8      1
80829     25913    1      1
80830     25914    1      1
80831     25915    1      1
80832     25916    1      1

[24268 rows x 3 columns]

In [22]:
sns.barplot(data=groupby,x='age',y=0,hue='album_id')

Error in callback <function flush_figures at 0x28d6685e0> (for post_execute):

KeyboardInterrupt: